services:
  bms_db:
    image: postgres:latest
    container_name: bms_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bms_db
      - POSTGRES_HOST=5432
    volumes:
      - ./docker_data/bms_db:/var/lib/postgresql/data
  bms:
    container_name: bms_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: ${DB_URL}
        PG_USER: ${DB_USER}
        PG_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql://bms_db:5432/postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - bms_db
