version: "3.9"

services:
  bms_db:
    image: postgres:latest
    container_name: bms_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bms_db
      - POSTGRES_HOST=5432
    volumes:
      - ./docker_data/bms_db:/var/lib/postgresql/data