server:
  port: 8080

grpc:
  server:
    port: 8000
  client:
    bms-review-summarizer:
      address: static://${BMS_REVIEW_SUMMARIZER_ADDRESS}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

bms-review-summarizer:
  tagsQuantity: ${BMS_REVIEW_SUMMARIZER_TAGS_QUANTITY}
  maxFeatures: ${BMS_REVIEW_SUMMARIZER_MAX_FEATURES}

spring:
  application:
    name: nascar-bms
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 10000
      pool-name: pg-pool
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
