services:
  bms_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bms_db
      - POSTGRES_HOST=5432
    volumes:
      - ./docker_data/bms_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d bms_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  bms:
    build:
      platforms:
        - linux/amd64
      context: ..
      args:
        DB_URL: ${DB_URL}
        PG_USER: ${DB_USER}
        PG_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      bms_db:
        condition: service_healthy
