services:
  bms:
    container_name: bms_app
    env_file:
      - .env
    build:
      context: .
      dockerfile: ../Dockerfile
      args:
        DB_URL: ${DB_URL}
        PG_USER: ${DB_USER}
        PG_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"