name: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "issue-*" ]

env:
  IMAGE_NAME: cr.yandex/crp67o7qqbgu7l8alg3o/bms

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      image_tags: ${{ steps.meta.outputs.tags }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
      -
        name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      -
        name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      -
        name: Build gradle image
        run: |
          ./gradlew bootBuildImage --imageName=${{ env.IMAGE_NAME }}

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ansible:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - run: echo '${{ toJSON(needs.docker.outputs) }}'
